server:
  port: 8090
  contextPath: /form

liquibase:
  change-log: "classpath:/db/changelog/change-log-1.0.xml"

security:
  basic:
    enabled: false

spring:
  output:
    ansi:
      enabled: always

